### ISSUE TITLE
The extension is not opening 

### ISSUE THREAD

**Issue by iva-system** [CupNoodles/ti-ext-itemsales#1]
The extension installed fine and i can see it under Sales=>Item Sales
when i click the icon it shows the following message:
(Something went wrong and the page cannot be displayed)
and the following error shows:

"ErrorException: Undefined array key 0
in /customers/e/0/d/localhost/httpd.www/demo/storage/framework/views/ac6fa33555cf967f9ad18c2f8495634e59cbe359.php:15Stack trace:
#0 /customers/e/0/d/localhost/httpd.www/demo/storage/framework/views/ac6fa33555cf967f9ad18c2f8495634e59cbe359.php(15): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Undefined array...', '/customers/e/0/...', 15)
#1 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(225): include('/customers/e/0/...')
#2 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(187): Admin\Classes\BaseWidget->makeFileContent('/customers/e/0/...', Array)
#3 /customers/e/0/d/localhost/httpd.www/demo/app/admin/widgets/Filter.php(137): Admin\Classes\BaseWidget->makePartial('filter/scope_da...', Array)
#4 /customers/e/0/d/localhost/httpd.www/demo/storage/framework/views/7fcc037aae52db5069f0b876b0cc0f44ab32c2c8.php(3): Admin\Widgets\Filter->renderScopeElement(Object(Admin\Classes\FilterScope))
#5 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(225): include('/customers/e/0/...')
#6 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(187): Admin\Classes\BaseWidget->makeFileContent('/customers/e/0/...', Array)
#7 /customers/e/0/d/localhost/httpd.www/demo/storage/framework/views/8d4246c8f33add8637209bc356777a178b1f3cd2.php(39): Admin\Classes\BaseWidget->makePartial('filter/filter_s...')
#8 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(225): include('/customers/e/0/...')
#9 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(187): Admin\Classes\BaseWidget->makeFileContent('/customers/e/0/...', Array)
#10 /customers/e/0/d/localhost/httpd.www/demo/app/admin/widgets/Filter.php(102): Admin\Classes\BaseWidget->makePartial('filter/filter')
#11 /customers/e/0/d/localhost/httpd.www/demo/app/admin/actions/ListController.php(283): Admin\Widgets\Filter->render()
#12 [internal function]: Admin\Actions\ListController->renderList()
#13 /customers/e/0/d/localhost/httpd.www/demo/vendor/tastyigniter/flame/src/Traits/ExtendableTrait.php(451): call_user_func_array(Array, Array)
#14 /customers/e/0/d/localhost/httpd.www/demo/app/admin/classes/AdminController.php(544): Admin\Classes\AdminController->extendableCall('renderList', Array)
#15 /customers/e/0/d/localhost/httpd.www/demo/storage/framework/views/6a521de2ecb55f36f28ee4502770ff6344e7841a.php(2): Admin\Classes\AdminController->__call('renderList', Array)
#16 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(225): include('/customers/e/0/...')
#17 /customers/e/0/d/localhost/httpd.www/demo/app/system/traits/ViewMaker.php(150): Admin\Classes\AdminController->makeFileContent('/customers/e/0/...')
#18 /customers/e/0/d/localhost/httpd.www/demo/app/admin/classes/AdminController.php(292): Admin\Classes\AdminController->makeView('index')
#19 /customers/e/0/d/localhost/httpd.www/demo/app/admin/classes/AdminController.php(228): Admin\Classes\AdminController->execPageAction('index', Array)
#20 /customers/e/0/d/localhost/httpd.www/demo/app/system/classes/Controller.php(115): Admin\Classes\AdminController->remap('index', Array)
#21 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): System\Classes\Controller->runAdmin('cupnoodles/item...')
#22 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('runAdmin', Array)
#23 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(System\Classes\Controller), 'runAdmin')
#24 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#25 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\Routing\Route->run()
#26 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /customers/e/0/d/localhost/httpd.www/demo/app/admin/middleware/LogUserLastSeen.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Admin\Middleware\LogUserLastSeen->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /customers/e/0/d/localhost/httpd.www/demo/vendor/tastyigniter/flame/src/Translation/Middleware/Localization.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Igniter\Flame\Translation\Middleware\Localization->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#37 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#46 /customers/e/0/d/localhost/httpd.www/demo/vendor/tastyigniter/flame/src/Router/CoreRouter.php(22): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Igniter\Flame\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#48 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 /customers/e/0/d/localhost/httpd.www/demo/vendor/tastyigniter/flame/src/Setting/Middleware/SaveSetting.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Igniter\Flame\Setting\Middleware\SaveSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /customers/e/0/d/localhost/httpd.www/demo/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /customers/e/0/d/localhost/httpd.www/demo/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /customers/e/0/d/localhost/httpd.www/demo/extensions/igniter/api/vendor/dingo/api/src/Http/Middleware/Request.php(111): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /customers/e/0/d/localhost/httpd.www/demo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /customers/e/0/d/localhost/httpd.www/demo/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}"

**Comment by CupNoodles** [comment]
Thanks for the bug report! I was able to reproduce the issue and have pushed up a new version, can you try it with the fixes on https://github.com/CupNoodles/ti-ext-itemsales/commit/38cc9243f3c53f4b1966d9428da49b4f579092f0?

**Comment by iva-system** [comment]
Perfect it works :)
Thank you so much
